Upgrade ft-poller from v5 to v7
Financial-Times/dotcom-page-kit pull request #950
Opened 2022-06-30 13:54 UTC by alexmuller

This is a breaking change in ft-poller which fixes a bug in that nothing listening to the `emit('error')` event results in an unhandled promise rejection warning that causes Node 16 apps to crash. It also drops support for Node 12.

See https://github.com/Financial-Times/ft-poller/pull/91 for context.

This change appears to be the first use of n-logger in Page Kit.

2022-07-20 15:01 UTC, joelcarr commented
Link to discussion about this PR on Slack: https://financialtimes.slack.com/archives/C3TJ6KXEU/p1656683125668959?thread_ts=1656507543.908159&cid=C3TJ6KXEU

Summary of discussion:
This is a good change as we need to catch errors when getting menu data. We do not and ideally should not use `n-logger` currently on Page Kit because in theory we should be throwing the error for the consuming app to catch. However if we start throwing errors, we will cause more "H10 app crashed because uncaught error" issues. For now we will use `n-logger` and write a comment to explain the temporary solution.

2022-07-20 15:07 UTC, joelcarr requested changes

2022-07-20 15:07 UTC, joelcarr commented on packages/dotcom-server-navigation/src/navigation.ts
> +      // In that case, continue to use the latest navigation we have available.
**request:** Please could we amend the comment to include that this is a temporary solution until there is a solution to the uncaught error issue?

2022-08-02 16:29 UTC, alexmuller commented
Sorry for the delay Joel. I've linked to a ticket where we can gather our thoughts if that works?

2022-08-03 08:58 UTC, joelcarr approved these changes
Lovely!

2022-08-03 10:39 UTC, alexmuller commented
Thanks! I don't think this will be a breaking change to the API so possibly just a minor or patch version.

2022-08-03 10:39 UTC, merged